# Generated by Django 3.2 on 2024-04-13 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='uuid',
        ),
        migrations.AddField(
            model_name='myuser',
            name='refresh_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='refresh_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='refresh_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
