# Generated by Django 3.2 on 2024-04-13 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240413_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('3102ea62-d333-4d56-a66b-ae51559c509f'), editable=False, unique=True),
        ),
    ]
