# Generated by Django 3.2 on 2024-04-15 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='refresh_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
